import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsDir = join(root, 'src', 'app', 'design-system', 'icons');

const library = JSON.parse(
    readFileSync(join(root, 'node_modules', 'lucide-static', 'icon-nodes.json'), 'utf8'),
);
const manifest = JSON.parse(readFileSync(join(iconsDir, 'icons.manifest.json'), 'utf8'));

const missing = manifest.filter((name) => !(name in library));

if (missing.length > 0) {
    console.error(`Unknown Lucide icons: ${missing.join(', ')}`);
    process.exit(1);
}

const camel = (name) => name.replace(/-(\w)/g, (_, letter) => letter.toUpperCase());

const body = [...manifest].sort().map((name) => {
const nodes = library[name]
    .map(([tag, attrs]) => `['${tag}', ${JSON.stringify(attrs)}]`)
    .join(', ');

    return `export const ${camel(name)}: IconNodes = [${nodes}];`;
});

writeFileSync(
join(iconsDir, 'icons.generated.ts'),
[
    '// Generated by tools/generate-icons.mjs from lucide-static. Do not edit by hand.',
    "// Add a name to icons.manifest.json and run 'npm run icons'.",
    '',
    "import { IconNodes } from './icon-nodes';",
    '',
    ...body,
    '',
].join('\n'),
    'utf8',
);

console.log(`icons: ${manifest.length} written to icons.generated.ts`);