<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>dfd1e992-13c1-4156-9c79-c6346d9f5949</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReactionLab.Application\ReactionLab.Application.csproj" />
    <ProjectReference Include="..\ReactionLab.Infrastructure\ReactionLab.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\ReactionLab.ServiceDefaults\ReactionLab.ServiceDefaults.csproj" />
  </ItemGroup>
  
</Project>
