// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReactionLab.Infrastructure.Persistence;

#nullable disable

namespace ReactionLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReactionLab.Domain.Elements.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtomicNumber")
                        .HasColumnType("integer")
                        .HasColumnName("atomic_number");

                    b.Property<decimal?>("BoilingPoint")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("boiling_point");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("display_color");

                    b.Property<string>("ElectronConfiguration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("electron_configuration");

                    b.Property<decimal?>("Electronegativity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("electronegativity");

                    b.Property<decimal>("Mass")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)")
                        .HasColumnName("mass");

                    b.Property<decimal?>("MeltingPoint")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("melting_point");

                    b.Property<string>("StateAtRoomTemperature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state_at_room_temperature");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("citext")
                        .HasColumnName("symbol");

                    b.Property<string>("_translations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("translations");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("search_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "ReactionLab.Domain.Elements.Element.Position#PeriodicPosition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Group")
                                .HasColumnType("integer")
                                .HasColumnName("periodic_group");

                            b1.Property<int>("Period")
                                .HasColumnType("integer")
                                .HasColumnName("period");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Radii", "ReactionLab.Domain.Elements.Element.Radii#AtomicRadii", b1 =>
                        {
                            b1.Property<decimal>("CovalentPicometers")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("covalent_radius_pm");

                            b1.Property<decimal?>("VanDerWaalsPicometers")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("van_der_waals_radius_pm");
                        });

                    b.HasKey("Id")
                        .HasName("pk_elements");

                    b.HasIndex("AtomicNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_elements_atomic_number");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_elements_symbol");

                    b.HasIndex("search_text")
                        .HasDatabaseName("ix_elements_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("search_text"), new[] { "gin_trgm_ops" });

                    b.ToTable("elements", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Reactions.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsReversible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversible");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("_translations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("translations");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<Guid[]>("reactant_signature")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("reactant_signature");

                    b.Property<string>("search_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Conditions", "ReactionLab.Domain.Reactions.Reaction.Conditions#ReactionConditions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Catalyst")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("catalyst");

                            b1.Property<decimal?>("Pressure")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("pressure_kpa");

                            b1.Property<decimal?>("Temperature")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("temperature_k");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Energetics", "ReactionLab.Domain.Reactions.Reaction.Energetics#Thermodynamics", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("ActivationEnergyKilojoulesPerMole")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("activation_energy_kj_per_mol");

                            b1.Property<decimal?>("EnthalpyChange")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("enthalpy_kj_per_mol");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Visualization", "ReactionLab.Domain.Reactions.Reaction.Visualization#VisualizationHint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("DurationMilliseconds")
                                .HasColumnType("integer")
                                .HasColumnName("animation_duration_ms");

                            b1.Property<string>("PresetKey")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("effect_preset_key");
                        });

                    b.HasKey("Id")
                        .HasName("pk_reactions");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_reactions_type");

                    b.HasIndex("reactant_signature")
                        .HasDatabaseName("ix_reactions_reactant_signature");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("reactant_signature"), "gin");

                    b.HasIndex("search_text")
                        .HasDatabaseName("ix_reactions_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("search_text"), new[] { "gin_trgm_ops" });

                    b.ToTable("reactions", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Substances.Substance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("formula");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_organic");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("StateAtRoomTemperature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state_at_room_temperature");

                    b.Property<string>("Structure")
                        .HasColumnType("jsonb")
                        .HasColumnName("structure");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(12, 5)
                        .HasColumnType("numeric(12,5)")
                        .HasColumnName("weight");

                    b.Property<string>("_translations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("translations");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("search_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_substances");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_substances_category");

                    b.HasIndex("Formula")
                        .HasDatabaseName("ix_substances_formula");

                    b.HasIndex("search_text")
                        .HasDatabaseName("ix_substances_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("search_text"), new[] { "gin_trgm_ops" });

                    b.ToTable("substances", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Reactions.Reaction", b =>
                {
                    b.OwnsMany("ReactionLab.Domain.Reactions.ReactionParticipant", "_participants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Coefficient")
                                .HasColumnType("integer")
                                .HasColumnName("coefficient");

                            b1.Property<Guid>("ReactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("reaction_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<string>("State")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("state");

                            b1.Property<Guid>("SubstanceId")
                                .HasColumnType("uuid")
                                .HasColumnName("substance_id");

                            b1.HasKey("Id")
                                .HasName("pk_reaction_participants");

                            b1.HasIndex("ReactionId")
                                .HasDatabaseName("ix_reaction_participants_reaction_id");

                            b1.HasIndex("SubstanceId")
                                .HasDatabaseName("ix_reaction_participants_substance_id");

                            b1.ToTable("reaction_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReactionId")
                                .HasConstraintName("fk_reaction_participants_reactions_reaction_id");
                        });

                    b.Navigation("_participants");
                });
#pragma warning restore 612, 618
        }
    }
}
