// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReactionLab.Infrastructure.Persistence;

#nullable disable

namespace ReactionLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReactionLabDbContext))]
    partial class ReactionLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReactionLab.Domain.Entities.Bond", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Atom1Index")
                        .HasColumnType("integer");

                    b.Property<int>("Atom2Index")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BondEnergy")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("BondLength")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<int>("BondType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MoleculeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MoleculeId");

                    b.ToTable("Bonds", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AtomicMass")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<int>("AtomicNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AtomicRadius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("BoilingPoint")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Density")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("DiscoveryInfo")
                        .HasColumnType("text");

                    b.Property<string>("DisplayColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ElectronConfiguration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Electronegativity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int?>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("InterestingFacts")
                        .HasColumnType("text");

                    b.Property<decimal?>("IonizationEnergy")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("MeltingPoint")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<decimal>("Radius3D")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("StateAtRoomTemp")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("AtomicNumber")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Elements", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Molecule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CommonNames")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IUPACName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InterestingFacts")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("boolean");

                    b.Property<string>("Model3DUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MolecularWeight")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SafetyInfo")
                        .HasColumnType("text");

                    b.Property<int>("StateAtRoomTemp")
                        .HasColumnType("integer");

                    b.Property<string>("Structure3D")
                        .HasColumnType("text");

                    b.Property<string>("Uses")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Molecules", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.MoleculeElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MoleculeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("MoleculeId", "ElementId")
                        .IsUnique();

                    b.ToTable("MoleculeElement", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActivationEnergy")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("AnimationDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("AnimationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CatalystInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DifficultyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("EffectPreset")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("EnthalpyChange")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Equation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EquationBalanced")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsExothermic")
                        .HasColumnType("boolean");

                    b.Property<string>("Mechanism")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReactionType")
                        .HasColumnType("integer");

                    b.Property<string>("RealWorldExamples")
                        .HasColumnType("text");

                    b.Property<decimal?>("RequiredPressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("RequiredTemperature")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("RequiresCatalyst")
                        .HasColumnType("boolean");

                    b.Property<string>("SafetyWarnings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.ReactionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coefficient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MoleculeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReactionId")
                        .HasDatabaseName("IX_ReactionParticipants_ReactionId");

                    b.HasIndex("ElementId", "Role")
                        .HasDatabaseName("IX_ReactionParticipants_ElementId_Role")
                        .HasFilter("\"Role\" = 0");

                    b.HasIndex("MoleculeId", "Role")
                        .HasDatabaseName("IX_ReactionParticipants_MoleculeId_Role")
                        .HasFilter("\"Role\" = 0");

                    b.ToTable("ReactionParticipants", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.ReactionTag", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ReactionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ReactionTags", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.UserExperiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkspaceState")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExperiments", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("BestScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserId", "ReactionId")
                        .IsUnique();

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Bond", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.Molecule", "Molecule")
                        .WithMany()
                        .HasForeignKey("MoleculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Molecule");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.MoleculeElement", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.Element", "Element")
                        .WithMany("MoleculeElements")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReactionLab.Domain.Entities.Molecule", "Molecule")
                        .WithMany("MoleculeElements")
                        .HasForeignKey("MoleculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Molecule");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.ReactionParticipant", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReactionLab.Domain.Entities.Molecule", "Molecule")
                        .WithMany("ReactionParticipants")
                        .HasForeignKey("MoleculeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReactionLab.Domain.Entities.Reaction", "Reaction")
                        .WithMany("Participants")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Molecule");

                    b.Navigation("Reaction");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.ReactionTag", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.Reaction", "Reaction")
                        .WithMany("ReactionTags")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactionLab.Domain.Entities.Tag", "Tag")
                        .WithMany("ReactionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.UserExperiment", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.User", "User")
                        .WithMany("Experiments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("ReactionLab.Domain.Entities.Reaction", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactionLab.Domain.Entities.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Element", b =>
                {
                    b.Navigation("MoleculeElements");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Molecule", b =>
                {
                    b.Navigation("MoleculeElements");

                    b.Navigation("ReactionParticipants");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Reaction", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("ReactionTags");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ReactionTags");
                });

            modelBuilder.Entity("ReactionLab.Domain.Entities.User", b =>
                {
                    b.Navigation("Experiments");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
