// Generated by tools/generate-icons.mjs from lucide-static. Do not edit by hand.
// Add a name to icons.manifest.json and run 'npm run icons'.

import { IconNodes } from './icon-nodes';

export const check: IconNodes = [['path', {"d":"M20 6 9 17l-5-5"}]];
export const chevronDown: IconNodes = [['path', {"d":"m6 9 6 6 6-6"}]];
export const circleAlert: IconNodes = [['circle', {"cx":"12","cy":"12","r":"10"}], ['line', {"x1":"12","x2":"12","y1":"8","y2":"12"}], ['line', {"x1":"12","x2":"12.01","y1":"16","y2":"16"}]];
export const info: IconNodes = [['circle', {"cx":"12","cy":"12","r":"10"}], ['path', {"d":"M12 16v-4"}], ['path', {"d":"M12 8h.01"}]];
export const loaderCircle: IconNodes = [['path', {"d":"M21 12a9 9 0 1 1-6.219-8.56"}]];
export const minus: IconNodes = [['path', {"d":"M5 12h14"}]];
export const plus: IconNodes = [['path', {"d":"M5 12h14"}], ['path', {"d":"M12 5v14"}]];
export const search: IconNodes = [['path', {"d":"m21 21-4.34-4.34"}], ['circle', {"cx":"11","cy":"11","r":"8"}]];
export const triangleAlert: IconNodes = [['path', {"d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"}], ['path', {"d":"M12 9v4"}], ['path', {"d":"M12 17h.01"}]];
export const x: IconNodes = [['path', {"d":"M18 6 6 18"}], ['path', {"d":"m6 6 12 12"}]];
